refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
    encoder:
      pattern: "[{d}][{l}][{t}] {m}{n}"

  file:
    kind: rolling_file
    path: "log/vulkan.log"
    append: false
    encoder:
      pattern: "[{d}][{l}][{t}] {m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 100 mb
      roller:
        kind: delete

root:
  level: warn
  appenders:
    - stdout

loggers:
  virtual_circus:
    level: debug
    additive: false
    appenders:
      - file
